Adicionado estrutura para regras
rudnetto/daciolo-chrome-extension pull request #4
Opened 2018-10-11 18:42 UTC by matheushf

Adicionado estrutura para regras regex, de início foi adicionado Hardcoded, precisando definir por onde será obtido o parâmetro `regra`, ou se será convertido dentro de um loop para usar todas as regras

2018-10-11 20:41 UTC, rudnetto commented on content.js
Essa linha está sendo utilizada em algum lugar?

2018-10-11 21:44 UTC, rudnetto requested changes

2018-10-11 21:44 UTC, rudnetto commented on content.js
> +var regra = 'regra1';
Remover variável não utilizada

2018-10-11 21:44 UTC, rudnetto commented on content.js
> +      rules.forEach(rule => {
Atualmente não estamos dando suporte para ES6, somente vanilla js. Alterar lógica de loop utilizando um `for`

2018-10-12 21:35 UTC, matheushf commented
Alterado

2018-10-12 21:47 UTC, rudnetto approved these changes

2018-10-12 21:47 UTC, merged

2018-10-12 22:23 UTC, rudnetto commented
Closes #2, but still some modifications are needed.